site_name: py-auto-docs
theme:
  name: "material"

plugins:
  - search:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - "example/"

nav:
  - "Home": README.md
  - "API Docs": example.md