[tool.poetry]
name = "py-auto-docs"
version = "0.0.1"
description = "Example module for automatically documenting a python module using mkdocs and mkdocstrings."
authors = ["James Hodgkinson <james@terminaloutcomes.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
mkdocs = "^1.5.3"
mkdocstrings = "^0.24.3"
mkdocs-material = "^9.5.17"

[tool.poetry.dev-dependencies]
pylint = "^3.1.0"
mypy = "^1.9"
black = "^24.3.0"
pytest = "^8.1.1"
mkdocstrings-python = "^1.9.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
