[tool.poetry]
name = "py-auto-docs"
version = "0.0.1"
description = "Example module for automatically documenting a python module using mkdocs and mkdocstrings."
authors = ["James Hodgkinson <james@terminaloutcomes.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
mkdocs = "^1.3.0"
mkdocstrings = "^0.18.1"
mkdocs-material = "^8.2.15"

[tool.poetry.dev-dependencies]
pylint = "^2.14.0"
mypy = "^0.960"
black = "^22.3.0"
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
