[tool.poetry]
name = "py-auto-docs"
version = "0.0.1"
description = "Example module for automatically documenting a python module using mkdocs and mkdocstrings."
authors = ["James Hodgkinson <james@terminaloutcomes.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
mkdocs = "^1.4.2"
mkdocstrings = "^0.19.0"
mkdocs-material = "^8.5.10"

[tool.poetry.dev-dependencies]
pylint = "^2.15.5"
mypy = "^0.991"
black = "^22.10.0"
pytest = "^7.2.0"
mkdocstrings-python = "^0.8.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
